export const state = {
	themeColor:'#fff',
	isShowFooter:true,
	footer_tab:0,
	secondNavData:[],
	subConData:[],
	subNavData:[],
	// host:'http://test.zhinengdayi.com',
	host:'http://zhinengdayi.com',
	// talkHost:'http://123.56.177.92:3000',
	talkHost:'http://zhinengdayi.com:3000',
	baseUrl:'/weixin/api',
	scode:'',
	timeout:200,
	contentType:2,
	infoId:0,
	catId: 0,
	isLogin:false,
	messageCount:0,
	scholl:null,
	footerMenu:[],
	loadingFlag:true,
	wxHost:'http://weixin.zhinengdayi.com', //微信服务端域名
	identify:'',
	sid:0,
	schListTab: 1,
	sdecode:false,
	sdecode2:false,
}
